apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      annotations:
        dapr.io/app-id: "publisher"
        dapr.io/enabled: "true"
        dapr.io/app-port: "5001"
        dapr.io/metrics-port: "9090"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
#        dapr.io/enable-app-health-check: "true"
#        dapr.io/app-health-check-path: "/actuator/health"
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: bibryam/publisher
          ports:
            - containerPort: 5001
