apiVersion: v1
kind: Service
metadata:
  labels:
    app: publisher
  name: publisher
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: publisher
  type: LoadBalancer
