apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: null
scopes: []
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: foo
